export const TASHKENT_DISTRICTS = [
  'BEKTEMIR',
  'CHILONZOR',
  'YASHNOBOD',
  'MIROBOD',
  'MIRZO_ULUGBEK',
  'SERGELI',
  'SHAYXONTOHUR',
  'OLMAZOR',
  'UCHTEPA',
  'YAKKASAROY',
  'YUNUSOBOD',
  'YANGIHAYOT',
];
